version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.api
    image: pretrained-app-api-development
    volumes:
      - ./api:/home/pn/api:Z
    network_mode: host
    environment:
      - API_ENV=development
    command: python development_server.py

  frontend:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.frontend
    image: pretrained-app-frontend-development
    volumes:
      - ./frontend:/home/node/pretrained-app/frontend:Z
    network_mode: host
    command: bash -c "cd /home/node/pretrained-app/frontend && npx expo start --web"

  nginx:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.nginx
    network_mode: host

  mongo:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.mongo
    container_name: app_mongo
    environment:
      MONGO_INITDB_DATABASE: "pretrained_app"
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/app_mongo_root_password
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_PASSWORD_FILE: /run/secrets/app_mongo_password
      MONGO_USER: "admin"
    secrets:
      - app_mongo_password
      - app_mongo_root_password
    volumes:
      - mongo:/data/db
    network_mode: host

secrets:
  app_mongo_password:
    file: ./stages/development/mongo/password
  app_mongo_root_password:
    file: ./stages/development/mongo/root_password

volumes:
  mongo:
