version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.api
    image: pretrained-app-api-development
    volumes:
      - ./api:/home/pn/api:Z
    network_mode: host
    command: python development_server.py

  frontend:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.frontend
    image: pretrained-app-frontend-development
    volumes:
      - ./frontend:/home/node/pretrained-app/frontend:Z
    network_mode: host
    command: bash -c "cd /home/node/pretrained-app/frontend && npx expo start --web"

  nginx:
    build:
      context: .
      dockerfile: stages/development/Dockerfile.nginx
    network_mode: host
