FROM nikolaik/python-nodejs:latest

USER pn

ENV LANG=C.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=C.UTF-8
ENV MODE=production

ENV APP_PATH=/home/pn/api
ENV PATH="${PATH}:/home/pn/.local/bin"
WORKDIR $APP_PATH
EXPOSE 5000
COPY --chown=pn:pn ./api/requirements.txt ./requirements.txt
RUN pip install setuptools==65.5.0 && \
    pip install numpy && \
    pip install waitress && \
    pip install -r requirements.txt
