version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: stages/production/Dockerfile.api
    image: pretrained-app-api-production
    network_mode: host

  frontend:
    build:
      context: .
      dockerfile: stages/production/Dockerfile.frontend
    image: pretrained-app-frontend-production
    network_mode: host

  nginx:
    build:
      context: .
      dockerfile: stages/production/Dockerfile.nginx
    image: nginx:1.23.2-alpine
    network_mode: host
    volumes:
      - ./stages/production/nginx:/etc/nginx/conf.d
