version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    command: bash -c  "cd /home/pn/pretrained-app/api && python production_server.py"
    network_mode: host

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    network_mode: host
    command: bash -c "cd /home/node/pretrained-app/frontend && npx serve web-build"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    network_mode: host
