FROM nikolaik/python-nodejs:latest
ENV LANG C.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL C.UTF-8
ENV APP_PATH=/home/pn/pretrained-app/
ENV MODE=production
USER pn
RUN mkdir -p $APP_PATH/api/.pytest_cache
ENV PATH "/home/pn/.local/bin:$PATH"
WORKDIR $APP_PATH
RUN pwd && ls -la --color
COPY . .

RUN cd $APP_PATH/api && \
    pip install setuptools==58.2.0 && \
    pip install waitress && \
    pip install -r requirements.txt
EXPOSE 5000
