version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    # volumes:
    #   - ./api/.:/home/pn/pretrained-app/api/.:Z
    command: bash -c  "cd /home/pn/pretrained-app/api && waitress-serve --call 'flaskr:create_app'"
    ports:
      - '5000:5000'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    network_mode: host
    command: bash -c "cd /home/node/pretrained-app/frontend && npx serve web-build"

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    network_mode: host
