name: API Production Docker Image

on:
  pull_request:
    branches: ["main"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Production Docker image
      run: docker build . --file stages/production/Dockerfile.api --tag api-production-image:$(date +%s)
