# This is a basic workflow to help you get started with Actions

name: Deploy to production

on:
  push:
    branches: ["main"]

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude=".git/*" --exclude="api/log/*" --exclude="frontend/node_modules/*" --exclude="tmp/" --filter=""
          path: ./
          remote_path: /home/deploy/pretrained-app/
          remote_host: ${{ secrets.HOST }}
          remote_port: 22
          remote_user: ${{ secrets.USER_NAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
      # - name: Deploy using ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd /home/deploy/pretrained-app
      #       ./script/deploy_to_production.sh
