# This is a basic workflow to help you get started with Actions

name: Deploy application

on:
  pull_request:
    branches: ["develop"]

jobs:
  deploy_production:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-regexp: 'Run .+? check'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/deploy/pretrained-app
            git pull origin develop
            docker-compose build
            docker-compose up -d
