name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Our congratulations! You are just create your first issue in pretrained app project. Next - try to solve and create pull request."
        pr-message: "Our congratulations! You are become an contributor! We are glad to review your code."
