name: Pylint

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    name: Run Pylint check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./api/requirements.txt
        pip install pylint
    - name: Analysing pretrained-app-api source code with pylint
      run: |
        ./script/run_pylint.sh
