name: Ward

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    name: Run Ward check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        mkdir -p ./api/log
        touch ./api/log/test.log
        pip install -r ./api/requirements.txt
    - name: Testing the code with ward
      run: |
        ./script/run_tests.sh
